### ISSUE TITLE
Single-branch Dialogue Builder

### ISSUE THREAD

**Issue by Zymus** [Zymus/Hummingbird#47]
I want to create an easy-to-use dialogue builder.

Node types:
* Display
* Prompt

I need it to be able to be codified into a YAML document, as well as be built in memory, hopefully using the same model.

I'd also like to be able to build them without each node being required to have a unique identifier.

I may need to have a "context" object which stores data from the participants.

*Example Dialogue:*
```yaml
dialogue:
  id: welcome
  nodes:
    - !display:0.0
      message: Welcome!
    - !prompt:0.0
      message: What is your name?
      propertyName: name
    - !display:0.0
      message: Hello, $name, nice to meet you.
```

```kotlin
dialogue("welcome") {
    display { "Welcome!" }
    promptFor("name") { "What is your name?" }
    display("name") { "Hello, \$name, nice to meet you." }
}
```
