### ISSUE TITLE
Player Admin Service

### ISSUE THREAD

**Issue by Zymus** [Zymus/Hummingbird#61]

**Comment by Zymus** [comment]
The player will be an entity that, through some method or another, contains all components needed for the player to interact with the game. It would contain a position, a form, party, pokedex, trainer card, etc. Everything specific to the player character. We'll see if we can keep the user or player separate from the player character, that way we don't initially limit it to 1 player.

I want to keep the entities logically close together. I don't want it to be flat, where absolutely every entity differs only by name. Otherwise you end up doing things like PlayerDialog01, PlayerDialog02, PlayerDialog03, etc. You just end up with a naming convention anyway, "quests start with q_", "items start with i_", things like that. 

So the data about a player's pokedex should be in only one place, their inventory, their pc, everything. Could look something like

```yaml
# player
zymus:
  inventory:
    - name: potion
      namespace: zephyrion
      quantity: 6
  pc:
    pokemon:
      - species:
    items:
  pokedex:
```

However, each of these components are managed by a different system/service, and that system/service doesn't necessarily need to know about all other systems. For instance, the potion in the inventory has Item data, and that Item data should initially, exist in only one place, and be referenced if it needs to be used. So I wouldn't have a new Item instance, I would just be pointing to an existing Item instance.
