### ISSUE TITLE
Namespace Resource System

### ISSUE THREAD

**Issue by Zymus** [Zymus/Hummingbird#76]

**Comment by Zymus** [comment]
A namespace resource is made up of a namespace and name. All namespaces are unique in name, as are all names. Only one instance of a name can exist in a namespace, and no two namespaces can share the same name.

This is different than a localized name.

Examples:
```yaml
# Item
namespace: zephyrion
name: potion
# Move
namespace: zephyrion
name: tackle
# Species
namespace: zephyrion
name: zephyrion
# Region
namespace: zephyrion
name: origin
# Type
namespace: zephyrion
name: fire
# Experience Group
namespace: zephyrion
name: erratic
# Effect
namespace: zephyrion
name: generate_pokemon
# Badge
namespace: zephyrion
name: twilight
# Currency
namespace: zephyrion
name: dollars
```

It defines the boundaries of the uniqueness. You can have a move `zephyrion:tackle` and `hardcore:tackle`. They're both a Tackle move, but one is from the `zephyrion` namespace, and one is from the `hardcore` namespace. The `hardcore` namespace doesn't exert control over all `tackle` moves, nor does `zephyrion`.

This will be more useful for things that require that degree of uniqueness. Older techniques used item id lists, where each unique item or move had a different number, usually starting from 0 and increasing from there. Names and a namespace though are easier to reason about, and the readability is much nicer.
